### ISSUE TITLE
A quand l'emoji :heart: dans le readMe à la place du <3

### ISSUE THREAD

**Issue by ErwannNevou** [DanGeffroy/hubfy#1]
Issue me, I issue back :heart:

**Comment by DanGeffroy** [comment]
Fixed <3

**Comment by DanGeffroy** [comment]
Fixed :heart:

**Comment by ErwannNevou** [comment]
:heartpulse:

**Comment by DanGeffroy** [comment]
:heart_decoration:

**Comment by ErwannNevou** [comment]
:two_hearts:

**Comment by DanGeffroy** [comment]
:heartbeat:

**Comment by ErwannNevou** [comment]
:sparkling_heart:

**Comment by DanGeffroy** [comment]
:heart_eyes:

**Comment by ErwannNevou** [comment]
:revolving_hearts:

**Comment by DanGeffroy** [comment]
![alt text](http://bestanimations.com/Signs&Shapes/Hearts/heart-pixel-animation322.gif)

**Comment by ErwannNevou** [comment]
![Bisounours](https://media.giphy.com/media/tnivTK2URZm7e/giphy.gif)

**Comment by DanGeffroy** [comment]
![alt text](http://www.reactiongifs.com/r/2013/07/heart-beating.gif)
